sudo: true
language: python
env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=2.7
services:
  - redis-server
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libevent-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env -c bioconda python=$PYTHON_VERSION biom-format requests pandas click==6.7 nose sqlite joblib nltk scikit-bio
  - source activate test-env
  - pip install flake8
  - git clone https://github.com/nicolasff/webdis
  - pushd webdis
  - make
  - ./webdis &
  - popd
  - alias md5=md5sum
  - pip install -e . --no-deps
script:
  - flake8 --ignore=E731 redbiom 
  - make test
